export const REPORT = {
  PROD: "production",
  ALM: "alarm",
  MC: "machine",
  MC_ENG: "machineEnergyReport",
  FLR: "assemblyEnergyReport",
  NA: "N/A",
  ENG: "energy",
  UTILITY: "utility",
  AXTEL: "axtel",
  ASSEMBLY: "assemblyWiesSummeryOeeReport",
  SHIFTWISE: "shift",
  DAYWISE: "day",
  MC_COMPARISON:"machineComparisonReport",
  PLANT_DASHBOARD:"plantsDashboardReport",
  PLANT_COMPARISON:"plantComparisonReport",
  DYNAMIC:"dynamic",
  OEE:"oee",
  MAINTENANCE:"maintenance",
  VIEWALLMACHINEMAINTENANCE:"viewAllMachineMaintenance",
};